# Mutations
mutation CreateUserProfile($username: String!, $email: String!, $displayname: String!) @auth(level: USER) {
 user_insert(
  data: {
    id: "auth.uid"
    username: $username
    email: $email
    displayname: $displayname
    role: "'reader'"
  }
 )
}

mutation CreateStory($title: String!, $genre: String!, $description: String) @auth(level: USER) {
  story_insert(
    data: {
      creatorId: "auth.uid"
      title: $title
      genre: $genre
      description: $description
      status: "'draft'"
    }
  ) {
    id
  }
}

mutation CreateComment($storyId: String!, $content: String!) @auth(level: USER) {
  comment_insert(
    data: {
      storyId: $storyId
      authorId: "auth.uid"
      content: $content
    }
  ) {
    id
  }
}

mutation CreateReaction($storyId: String!, $reactionType: String!) @auth(level: USER) {
    reaction_insert(
        data: {
            storyId: $storyId
            userId: "auth.uid"
            reactionType: $reactionType
        }
    ) {
        id
    }
}
