# Queries
query GetUserProfile($userId: String!) @auth(level: USER) {
  User(id: $userId) {
    id
    username
    email
    displayname
    avatarUrl
    role
    createdAt
  }
}

query GetStoryWithContent($storyId: String!) {
  story(id: $storyId) {
    id
    title
    genre
    description
    coverImageUrl
    status
    createdAt
    storyContent {
      id
      textContent
      pageNumber
    }
  }
}
